version: '3.8'
services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html/
    restart: always
    networks:
      - inception_net
    depends_on:
      - wordpress
  wordpress:
    depends_on: 
      - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp_vol:/var/www/html/
    restart: always
    networks:
      - inception_net
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        - WP_DATABASE_NAME=${WP_DATABASE_NAME}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASS=${MYSQL_PASS}
        - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mdb_vol:/var/lib/mysql
    restart: always
    networks:
        - inception_net

networks:
  inception_net:
    name: inception_net
    driver: bridge

volumes:
  wp_vol:
    name: "word_volume"
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/trubat-d/data/wordpress/"
  mdb_vol:
    name: "mariadb_volume"
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/trubat-d/data/mariadb/"